/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_maku_free: (a: number, b: number) => void;
export const maku_add_file: (a: number, b: number, c: number, d: number, e: number) => void;
export const maku_beams: (a: number) => [number, number];
export const maku_boot: (a: number, b: number, c: number, d: number, e: number) => void;
export const maku_cells: (a: number) => [number, number];
export const maku_channel_num: (a: number, b: number, c: number) => number;
export const maku_channel_vec: (a: number, b: number, c: number) => [number, number];
export const maku_cmd_ticks: (a: number) => [number, number];
export const maku_command: (a: number, b: number, c: number) => void;
export const maku_current_pattern: (a: number) => [number, number];
export const maku_dots: (a: number) => [number, number];
export const maku_entity_count: (a: number) => number;
export const maku_flashes: (a: number, b: number) => [number, number];
export const maku_graze: (a: number) => number;
export const maku_hits: (a: number) => number;
export const maku_iframes: (a: number) => number;
export const maku_input_num: (a: number, b: number, c: number, d: number) => void;
export const maku_input_vec2: (a: number, b: number, c: number, d: number, e: number) => void;
export const maku_lives: (a: number) => number;
export const maku_new: (a: number, b: number) => number;
export const maku_patterns: (a: number) => [number, number];
export const maku_paused: (a: number) => number;
export const maku_player_pos: (a: number) => [number, number];
export const maku_positions: (a: number, b: number, c: number) => [number, number];
export const maku_restart: (a: number) => void;
export const maku_running: (a: number) => number;
export const maku_seek: (a: number, b: number) => void;
export const maku_select: (a: number, b: number) => void;
export const maku_status: (a: number) => [number, number];
export const maku_step: (a: number, b: number) => void;
export const maku_tick: (a: number) => number;
export const maku_timeline: (a: number) => [number, number];
export const maku_toggle_pause: (a: number) => void;
export const stdlibSource: (a: number, b: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
