use crate::contract::*;
use sha2::{Digest, Sha256};
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFixture {
    pub source: String,
    pub source_sha256: String,
    pub workload_sha256: String,
    pub input_tape_sha256: String,
}

pub fn sha256(bytes: impl AsRef<[u8]>) -> String {
    format!("{:x}", Sha256::digest(bytes.as_ref()))
}

pub fn load_workload(path: &Path) -> Result<Workload, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let workload: Workload = serde_json::from_slice(&bytes).map_err(|e| format!("parse {}: {e}", path.display()))?;
    workload.validate()?;
    Ok(workload)
}

/// Emit canonical, self-contained source. It deliberately has no imports, so
/// this byte sequence is also the expanded source hashed by both hosts.
pub fn generate(workload: &Workload) -> Result<GeneratedFixture, String> {
    workload.validate()?;
    let source = match workload.family {
        WorkloadFamily::BulletScale => generate_bullets(workload)?,
        WorkloadFamily::Collision => generate_collision(workload)?,
        WorkloadFamily::Rules => generate_rules(workload)?,
        other => return Err(format!("generator for {other:?} is not implemented")),
    };
    let canonical_workload = serde_json::to_vec(workload).map_err(|e| e.to_string())?;
    let canonical_tape = serde_json::to_vec(&workload.input_tape).map_err(|e| e.to_string())?;
    Ok(GeneratedFixture {
        source_sha256: sha256(&source),
        workload_sha256: sha256(canonical_workload),
        input_tape_sha256: sha256(canonical_tape),
        source,
    })
}

fn keyword(value: Option<&str>, fallback: &str) -> Result<String, String> {
    let value = value.unwrap_or(fallback);
    if value.is_empty() || !value.bytes().all(|c| c.is_ascii_alphanumeric() || b"-_/".contains(&c)) {
        return Err(format!("invalid generated keyword {value:?}"));
    }
    Ok(format!(":{value}"))
}

fn figure(workload: &Workload) -> String {
    match workload.motion.shape {
        MotionShape::Static => format!("(circle {} (linear p[0 0]))", workload.entities.plateau),
        MotionShape::Linear => format!("(circle {} (linear p[{} 0]))", workload.entities.plateau, workload.motion.speed),
        MotionShape::Polar => format!("(circle {} (polar p[{} 0]))", workload.entities.plateau, workload.motion.speed),
        MotionShape::Composed => format!("(circle {} ((rot 0) (linear p[{} 0])))", workload.entities.plateau, workload.motion.speed),
    }
}

fn generate_bullets(workload: &Workload) -> Result<String, String> {
    if workload.collision.geometry != ColliderGeometry::None || workload.rules.class != RuleClass::None {
        return Err("bullet-scale fixtures cannot include collision or rule axes".into());
    }
    let family = keyword(workload.render.family.as_deref(), "circle")?;
    let color = keyword(workload.render.color.as_deref(), "red")?;
    let variant = keyword(workload.render.variant.as_deref(), "w")?;
    let mut source = String::from(";; generated by maku-bench-generator-v1; do not edit\n");
    if workload.render.shape != RenderKind::None {
        if !matches!(workload.render.shape, RenderKind::PointBasic | RenderKind::PointTinted | RenderKind::PointRecolor) {
            return Err("bullet-scale v1 supports point or no rendering".into());
        }
        source.push_str("(defrender-kind :sprite\n  {:geometry :point\n   :fields {:family :sym :color :sym :variant :sym :scale :num}})\n\n");
        for _ in 0..workload.render.layers {
            source.push_str("(deftick\n  (map (fn [e]\n         (render {:kind :sprite :shape :point\n                  :x e.pos.x :y e.pos.y :theta e.pos.th\n                  :scale (default e.scale 1) :alpha 1 :hue 0\n                  :family e.family :color e.color :variant e.variant}))\n       (entities-where (fn [e] (= e.bench-kind :bullet)))))\n\n");
        }
    }
    source.push_str(&format!(
        "(defpattern bench []\n  (spawn {}\n         {{:bench-kind :bullet :render :sprite :family {} :color {} :variant {} :scale 1}}))\n",
        figure(workload), family, color, variant
    ));
    Ok(source)
}

fn contact_count(density: ContactDensity, total: usize) -> usize {
    match density {
        ContactDensity::None => 0,
        ContactDensity::Sparse => total / 100,
        ContactDensity::Controlled => total / 2,
        ContactDensity::Dense => total,
    }
}

fn circle_spawn(count: usize, radius: f64, layer: &str, collider_radius: f64) -> String {
    if count == 0 { return String::new(); }
    format!("    (spawn (circle {count} (pose c[{radius} 0]))\n           (circle-collider {{:layer :{layer} :r {collider_radius}}})\n           {{:render :hidden :bench-kind :collider}})\n")
}

fn capsule_spawn(count: usize, radius: f64, name: &str) -> String {
    if count == 0 { return String::new(); }
    format!("    (spawn (circle {count} ((pose c[{radius} 0]) (curve {{:u-max 0.01 :width 0}})))\n           {name}\n           {{:render :hidden :bench-kind :collider}})\n")
}

fn generate_collision(workload: &Workload) -> Result<String, String> {
    if workload.entities.plateau % 2 != 0 || workload.collision.query_pairs == 0 {
        return Err("collision plateau must be even and query_pairs nonzero".into());
    }
    if workload.entities.plateau / 2 % workload.collision.query_pairs as usize != 0 {
        return Err("source count must divide evenly across query pairs".into());
    }
    if workload.rules.class != RuleClass::None || workload.render.layers != 0 {
        return Err("collision one-axis fixtures cannot include rule or render axes".into());
    }
    let source_total = workload.entities.plateau / 2;
    let per_pair = source_total / workload.collision.query_pairs as usize;
    let contacts = contact_count(workload.collision.contact_density, per_pair);
    let noncontacts = per_pair - contacts;
    let collider_radius = (10.0 / per_pair.max(1) as f64).min(0.01);
    let mut source = String::from(";; generated by maku-bench-generator-v1; do not edit\n");
    if workload.collision.geometry == ColliderGeometry::CapsuleChain {
        for pair in 0..workload.collision.query_pairs {
            source.push_str(&format!("(defcollider :parametric bench-chain-{pair} [e ctx]\n  (capsule-chain-collider {{:layer :bench-src-{pair} :r {collider_radius} :u-max 0.01 :resolution 0.01 :width 0}}))\n"));
        }
        source.push('\n');
    }
    for pair in 0..workload.collision.query_pairs {
        source.push_str(&format!("(deftick (map (fn [[a b]] (when 0 (event :never))) (collisions :bench-src-{pair} :bench-dst-{pair})))\n"));
    }
    source.push_str("\n(defpattern bench []\n  (par\n");
    for pair in 0..workload.collision.query_pairs {
        let src = format!("bench-src-{pair}");
        let dst = format!("bench-dst-{pair}");
        match workload.collision.geometry {
            ColliderGeometry::Circle => {
                source.push_str(&circle_spawn(contacts, 6.0, &src, collider_radius));
                source.push_str(&circle_spawn(noncontacts, 3.0, &src, collider_radius));
            }
            ColliderGeometry::CapsuleChain => {
                source.push_str(&capsule_spawn(contacts, 6.0, &format!("bench-chain-{pair}")));
                source.push_str(&capsule_spawn(noncontacts, 3.0, &format!("bench-chain-{pair}")));
            }
            ColliderGeometry::None => return Err("collision fixture requires collider geometry".into()),
        }
        source.push_str(&circle_spawn(contacts, 6.0, &dst, collider_radius));
        source.push_str(&circle_spawn(noncontacts, 9.0, &dst, collider_radius));
    }
    source.push_str("  ))\n");
    Ok(source)
}

fn generate_rules(workload: &Workload) -> Result<String, String> {
    if workload.collision.geometry != ColliderGeometry::None || workload.rules.class == RuleClass::None {
        return Err("rule fixtures require a rule class and no collision axis".into());
    }
    let matched = match workload.rules.match_rate {
        MatchRate::None => 0,
        MatchRate::Half => workload.entities.plateau / 2,
        MatchRate::All => workload.entities.plateau,
    };
    let unmatched = workload.entities.plateau - matched;
    let mut source = String::from(";; generated by maku-bench-generator-v1; do not edit\n");
    if workload.rules.class == RuleClass::RenderOnly {
        source.push_str("(defrender-kind :sprite\n  {:geometry :point\n   :fields {:family :sym :color :sym :variant :sym :scale :num}})\n\n");
    }
    if workload.rules.class == RuleClass::MaskedUpdate {
        source.push_str("(defchannel $bench-actions (sum-entities {:bench-kind :rule} :bench-actions))\n\n");
    }
    for rule in 0..workload.rules.count {
        let action = match workload.rules.class {
            RuleClass::FilterOnly => format!("(when 0 (event :never-{rule}))"),
            RuleClass::RenderOnly => format!("(render {{:kind :sprite :shape :point :x e.pos.x :y e.pos.y :theta 0 :scale 1 :alpha 1 :hue {rule} :family :circle :color :red :variant :w}})"),
            RuleClass::MaskedUpdate => "(change-col e :bench-actions (fn [x] (+ (default x 0) 1)))".to_string(),
            RuleClass::EffectAction => format!("(event :bench-effect-{rule})"),
            RuleClass::None => unreachable!(),
        };
        source.push_str(&format!("(deftick\n  (map (fn [e] {action})\n       (entities-where (fn [e] (and (= e.bench-match 1) (< {rule} {}))))))\n\n", rule + 1));
    }
    source.push_str("(defpattern bench []\n  (par\n");
    if matched > 0 {
        source.push_str(&format!("    (spawn (circle {matched} (pose c[4 0])) {{:render :hidden :bench-kind :rule :bench-match 1 :bench-actions 0}})\n"));
    }
    if unmatched > 0 {
        source.push_str(&format!("    (spawn (circle {unmatched} (pose c[8 0])) {{:render :hidden :bench-kind :rule :bench-match 0 :bench-actions 0}})\n"));
    }
    source.push_str("  ))\n");
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::*;
    use maku::sim::Sim;

    fn tiny() -> Workload {
        serde_json::from_str(include_str!("../../../bench/workloads/v1/bullets-1k.json")).unwrap()
    }

    fn run_fixture(workload: &Workload) {
        let generated = generate(workload).unwrap();
        let mut sim = Sim::load(&generated.source, Some("bench")).unwrap();
        sim.resize_entity_capacity(workload.entities.capacity.unwrap()).unwrap();
        sim.step().unwrap();
        let verification = crate::verify(&mut sim, workload);
        assert!(verification.valid, "{}: {:?}", workload.id, verification.errors);
    }

    #[test]
    fn bullet_generation_is_stable_and_semantically_valid() {
        let workload = tiny();
        assert_eq!(generate(&workload).unwrap(), generate(&workload).unwrap());
        run_fixture(&workload);
    }

    #[test]
    fn collision_and_rule_families_generate_valid_cards() {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("../../bench/workloads/v1");
        for name in [
            "collision-circle-controlled-normal.json",
            "collision-capsule-chain-controlled-normal.json",
            "rules-filter-only-half.json",
            "rules-render-only-half.json",
            "rules-masked-update-half.json",
            "rules-effect-action-half.json",
        ] {
            let workload = load_workload(&root.join(name)).unwrap();
            run_fixture(&workload);
        }
    }
}
