use crate::contract::*;
use sha2::{Digest, Sha256};
use std::path::Path;

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct GeneratedFixture {
    pub source: String,
    pub source_sha256: String,
    pub workload_sha256: String,
    pub input_tape_sha256: String,
}

pub fn sha256(bytes: impl AsRef<[u8]>) -> String {
    format!("{:x}", Sha256::digest(bytes.as_ref()))
}

pub fn load_workload(path: &Path) -> Result<Workload, String> {
    let bytes = std::fs::read(path).map_err(|e| format!("read {}: {e}", path.display()))?;
    let workload: Workload = serde_json::from_slice(&bytes).map_err(|e| format!("parse {}: {e}", path.display()))?;
    workload.validate()?;
    Ok(workload)
}

/// Emit canonical, self-contained source. It deliberately has no imports, so
/// this byte sequence is also the expanded source hashed by both hosts.
pub fn generate(workload: &Workload) -> Result<GeneratedFixture, String> {
    workload.validate()?;
    let source = match workload.family {
        WorkloadFamily::BulletScale => generate_bullets(workload)?,
        other => return Err(format!("generator for {other:?} is not implemented")),
    };
    let canonical_workload = serde_json::to_vec(workload).map_err(|e| e.to_string())?;
    let canonical_tape = serde_json::to_vec(&workload.input_tape).map_err(|e| e.to_string())?;
    Ok(GeneratedFixture {
        source_sha256: sha256(&source),
        workload_sha256: sha256(canonical_workload),
        input_tape_sha256: sha256(canonical_tape),
        source,
    })
}

fn keyword(value: Option<&str>, fallback: &str) -> Result<String, String> {
    let value = value.unwrap_or(fallback);
    if value.is_empty() || !value.bytes().all(|c| c.is_ascii_alphanumeric() || b"-_/".contains(&c)) {
        return Err(format!("invalid generated keyword {value:?}"));
    }
    Ok(format!(":{value}"))
}

fn figure(workload: &Workload) -> String {
    match workload.motion.shape {
        MotionShape::Static => format!("(circle {} (linear p[0 0]))", workload.entities.plateau),
        MotionShape::Linear => format!("(circle {} (linear p[{} 0]))", workload.entities.plateau, workload.motion.speed),
        MotionShape::Polar => format!("(circle {} (polar p[{} 0]))", workload.entities.plateau, workload.motion.speed),
        MotionShape::Composed => format!("(circle {} ((rot 0) (linear p[{} 0])))", workload.entities.plateau, workload.motion.speed),
    }
}

fn generate_bullets(workload: &Workload) -> Result<String, String> {
    if workload.collision.geometry != ColliderGeometry::None || workload.rules.class != RuleClass::None {
        return Err("bullet-scale fixtures cannot include collision or rule axes".into());
    }
    let family = keyword(workload.render.family.as_deref(), "circle")?;
    let color = keyword(workload.render.color.as_deref(), "red")?;
    let variant = keyword(workload.render.variant.as_deref(), "w")?;
    let mut source = String::from(";; generated by maku-bench-generator-v1; do not edit\n");
    if workload.render.shape != RenderKind::None {
        if !matches!(workload.render.shape, RenderKind::PointBasic | RenderKind::PointTinted | RenderKind::PointRecolor) {
            return Err("bullet-scale v1 supports point or no rendering".into());
        }
        source.push_str("(defrender-kind :sprite\n  {:geometry :point\n   :fields {:family :sym :color :sym :variant :sym :scale :num}})\n\n");
        for _ in 0..workload.render.layers {
            source.push_str("(deftick\n  (map (fn [e]\n         (render {:kind :sprite :shape :point\n                  :x e.pos.x :y e.pos.y :theta e.pos.th\n                  :scale (default e.scale 1) :alpha 1 :hue 0\n                  :family e.family :color e.color :variant e.variant}))\n       (entities-where (fn [e] (= e.bench-kind :bullet)))))\n\n");
        }
    }
    source.push_str(&format!(
        "(defpattern bench []\n  (spawn {}\n         {{:bench-kind :bullet :render :sprite :family {} :color {} :variant {} :scale 1}}))\n",
        figure(workload), family, color, variant
    ));
    Ok(source)
}

#[cfg(test)]
mod tests {
    use super::*;
    use maku::{render::RenderItem, sim::Sim};

    fn tiny() -> Workload {
        serde_json::from_str(include_str!("../../../bench/workloads/v1/bullets-1k.json")).unwrap()
    }

    #[test]
    fn bullet_generation_is_stable_and_semantically_valid() {
        let workload = tiny();
        let a = generate(&workload).unwrap();
        let b = generate(&workload).unwrap();
        assert_eq!(a, b);
        let mut sim = Sim::load(&a.source, Some("bench")).unwrap();
        sim.resize_entity_capacity(workload.entities.capacity.unwrap()).unwrap();
        sim.step().unwrap();
        assert_eq!(sim.world.entities.len(), workload.expect.live_entities);
        let frame = sim.render_frame();
        let lanes: usize = frame.iter().map(|item| match item {
            RenderItem::Row(_) => 1,
            RenderItem::Batch(batch) => batch.len,
        }).sum();
        assert_eq!(lanes, workload.expect.render_lanes);
    }
}
